# Generated by Django 5.2.3 on 2025-06-22 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo letras mayúsculas A-Z.')])),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo letras mayúsculas A-Z.')])),
                ('primer_nombre', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo letras mayúsculas A-Z.')])),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Solo letras mayúsculas A-Z y espacios.')])),
                ('pais_empleo', models.CharField(choices=[('Colombia', 'Colombia'), ('Estados Unidos', 'Estados Unidos')], default='Colombia', max_length=20)),
                ('tipo_identificacion', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte'), ('Permiso Especial', 'Permiso Especial')], max_length=30)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo números.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('area', models.CharField(choices=[('Administración', 'Administración'), ('Financiera', 'Financiera'), ('Compras', 'Compras'), ('Infraestructura', 'Infraestructura'), ('Operación', 'Operación'), ('Talento Humano', 'Talento Humano'), ('Servicios Varios', 'Servicios Varios')], max_length=20)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employees',
                'unique_together': {('tipo_identificacion', 'numero_identificacion')},
            },
        ),
    ]
